name: Test scheduler

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger downstream workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: main.yml
          ref: branch-to-schedule-on